version: "3"

services: 
  label-studio:
    container_name: label-studio
    build: .
    working_dir: /label-studio
    volumes:
      - ./my_project:/label-studio/my_project
    command: "label-studio start-multi-session --use-gevent --root-dir ./session_projects --host 0.0.0.0"
    ports: 
      - "8081:8080"
    restart: always